// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Achievement achievement
//
// swagger:model achievement
type Achievement struct {

	// achievement Id
	// Required: true
	// Read Only: true
	AchievementID int64 `json:"achievementId"`
}

// Validate validates this achievement
func (m *Achievement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAchievementID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Achievement) validateAchievementID(formats strfmt.Registry) error {

	if err := validate.Required("achievementId", "body", int64(m.AchievementID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Achievement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Achievement) UnmarshalBinary(b []byte) error {
	var res Achievement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
